### ISSUE TITLE
Terms of Use / Disclaimer Page

### ISSUE THREAD

**Issue by heathharrelson** [OCTRI/phenotypr-body#27]
## Description

Julie M. envisions a disclaimer about the use of the website, there is a need to establish that no data is collected and that the application is not intended to replace/substitute for an official MD diagnosis.

## User Story

As program manager, I want a terms of use/disclaimer page or section on the website

so that all users are required to view and agree to terms before using the application.

## Acceptance Criteria

 * User is presented full details of terms of use/disclaimer
 * User is able to check a box/agree to terms of use
 * Terms of Use are required for every visit and to each section of the application

## Dependencies

 * Team will provide final set of terms of use

**Comment by heathharrelson** [comment]
Phenotypr terms link provided by Kara: https://phenotypr.com/terms.html

**Comment by kirenotneb** [comment]
Kara provided updated language to be used on the terms of use page:

> This tool does not provide medical advice. It is intended for informational and educational purposes only. By submitting information through the Phenotpyr platform you understand and accept the [terms of use](https://phenotypr.com/terms.html) to this site.

She also indicated that we may want to evaluate another tool for inspiration regarding how ToU are presented:

> I also wanted to point you to another tool we have, [Thermia](http://thermia.io/), which has a pop up disclaimer. Thought you might be interested in having a look at it, though I do think the way we have our layout currently is preferred.
