### ISSUE TITLE
Body Map / Questionnaire

### ISSUE THREAD

**Issue by heathharrelson** [OCTRI/phenotypr-body#29]
## Description

The idea is to display a high level list of 17 anatomy terms to get yes/no answers from the user. Ideally, the autocomplete search results would pre-select corresponding anatomy terms in the display. 

## User Story

As a user, I need a way to select individual anatomy systems that correspond to any observed phenotypic abnormalities

So I can provide additional information to the body diagnosis tool.

## Acceptance Criteria

Users can provide yes/no answers to the 17 high level anatomy terms

## Dependencies

Team will provide a list of the 17 high level anatomy terms

**Comment by jmcmurry** [comment]
High level terms are [here](https://docs.google.com/spreadsheets/d/15CzUagU6QVOmVfKown2u9evy26N8by62XOCGAkKr6b4/edit#gid=0).  I count only 17; some of these could be broken down, in theory. @mellybelly please advise

**Comment by kirenotneb** [comment]
@jmcmurry we don't have access to that Google doc. Can you please share it with @heathharrelson and myself?

**Comment by jmcmurry** [comment]
@mellybelly has OK'd these

**Comment by jmcmurry** [comment]
I changed the access so that all can view; I don't have heath's address.
