### ISSUE TITLE
Search for terms for incomplete systems

### ISSUE THREAD

**Issue by kirenotneb** [OCTRI/phenotypr-body#49]
## Description

Related to #29, users should be presented the opportunity to search for terms for selected body systems.

## User story

As a user, I need to be presented with the body systems for which I have not added any relevant terms.

So that I can improve the information provided to me from the tool.

## Acceptance criteria

* The user will be prompted to add terms relevant to the select body systems.
* Terms will be filtered by the limited to the selected body systems.

## Dependencies

Instruction as to how the solr index can be filtered by the high level body system HPO terms.

**Comment by kshefchek** [comment]
Given three high level categories as an example:

Abnormality of the kidney: HP:0000077 
Abnormality of the musculature: HP:0003011
Abnormality of the skin: HP:0000951

And the user wants to facet on all three.  Multiple facets can be applied by using the solr fq param, the phenotype_closure field, and an OR filter, eg:

    fq=phenotype_closure:"HP:0000077" OR phenotype_closure:"HP:0003011" OR phenotype_closure:"HP:0000951"


For example:
https://solr.monarchinitiative.org/solr/hpo-pl/select/?q=*:*&wt=json&rows=200&fq=phenotype_closure:%22HP:0000077%22%20OR%20phenotype_closure:%22HP:0003011%22%20OR%20phenotype_closure:%22HP:0000951%22

**Comment by kshefchek** [comment]
cc @mellybelly @jmcmurry to provide terms

**Comment by kshefchek** [comment]
As a starting point we could use all direct subclasses of phenotypic abnormality, they are enumerated here: https://hpo.jax.org/app/browse/term/HP:0000118

**Comment by kirenotneb** [comment]
Looks like those are a good first step, @kshefchek . This should definitely be used to accomplish #29 .

**Comment by jmcmurry** [comment]
I think that this can now be closed; please advise

**Comment by kirenotneb** [comment]
@jmcmurry, yes it can be closed at this time. We may have some additional styling to add, but will add that eventually.
