### ISSUE TITLE
Feedback on tool

### ISSUE THREAD

**Issue by kirenotneb** [OCTRI/phenotypr-body#50]
## Description

As a means to judge the efficacy of the tool, users should be able to provide limited feedback as to their experience.

## User Story

As a user I want to indicate if the tool provided my with the information I expected.

So that I can convey the effectiveness of the tool to the investigators.

## Acceptance Criteria

* Provide user with a mechanism to identify if the tool provided them with the information they required or not.
* Should not allow the user to enter PHI
* Should be a simple Boolean response.
* Will be persisted along with the searched terms.

## Dependencies

* The persistence API must accept the Boolean value as part of the submission.

**Comment by jmcmurry** [comment]
Can we make use of local storage? Otherwise patient could go through a lot of hassle only to have the session wiped out.

**Comment by kirenotneb** [comment]
@jmcmurry this sounds like an interesting feature we can add in the future. If you could, please create a new issue describing what you envision.

**Comment by heathharrelson** [comment]
The user is now asked for feedback on whether they have been able to find the desired conditions at [steps 3 and 5 of the workflow implemented for #58](https://github.com/OCTRI/phenotypr-body/issues/58). I have opened issue #71 for caching user data to local storage.
