### ISSUE TITLE
Include instructions about entering each symptom once.

### ISSUE THREAD

**Issue by jmcmurry** [OCTRI/phenotypr-body#52]
If you have experienced a symptom that fits in more than one category, you only need to enter it once.

**Comment by heathharrelson** [comment]
@jmcmurry The application ensures that a given HPO ID can only be added to the list of selected terms once. Given that, is this still required?

**Comment by jmcmurry** [comment]
Let's pick our battles and not worry about it then. However, this should be flagged as a question to ask users. Would it be disorienting or not to exclude a term which was already selected.

**Comment by jmcmurry** [comment]
It now makes sense to me why you wouldn't have seen this as a problem; I think that this issue is now overtaken by events. With the simplified approach, the page-by-page for each system that Melissa and I had originally understood would be built is not being built, so this is unlikely to be a problem that needs to be addressed at all.
