### ISSUE TITLE
Work flow of the system

### ISSUE THREAD

**Issue by kirenotneb** [OCTRI/phenotypr-body#58]
## Description

The Phenotypr Body tool allows users to self-identify phenotypic abnormalities using an unconstrained approach for describing their symptoms, enabling them to drive the process.  It also must encourage the user to be as complete as possible in identifying symptoms to ensure the most complete representation of any potential phenotypical abnormalities.

## User Story

As a user I want to:

1. Select the high-level categories of body systems so that I can limit my search to only the categories of symptoms that apply to me. 
2. Search for HPO terms using lay-person language.
3. Provide feedback whether the search provided me the symptoms I sought so that I can either search again or get my report.
4. If the initial search did not provide the results I was looking for search again without being limited by the categories I initially indicated, but optionally select a single category at a time so that I can further refine my symptoms.
5. Upon completing my search, I wish to provide feedback about the tool, if it provided the symptoms or not.
6. Get a report summarizing the the symptoms I found.

![phenotypr work flow 1](https://user-images.githubusercontent.com/229781/43926540-731b2c44-9bdf-11e8-96a6-cb8571260ddb.png)

## Acceptance Criteria

* The user can successfully navigate from selecting the high-level categories of body systems to a report.

**Comment by jmcmurry** [comment]
+1; it occurs to me though that we are leaving the terms on the floor except for download. Do we need a mechanism to report back centrally the verdict of whether all symptoms could be found? 
Also, this is picky but "Were you" is spelled wrong.

**Comment by kirenotneb** [comment]
The system now executes the workflow as described in above image. There is no navigation in the UI to return to a previous step, although users can use the back button to navigate their history. From a usability perspective this matches what users would expect and allows them to refine their terms.

**Comment by jmcmurry** [comment]
ok great thanks
