### ISSUE TITLE
Open and faceted search of symptoms

### ISSUE THREAD

**Issue by kirenotneb** [OCTRI/phenotypr-body#59]
## Description

As the Human Phenotype Ontology contains a large number of terms it may be difficult to find the specific term that correlates with a lay-person term. In order to enable users to find exactly what they are looking for it would be useful to search against the entire ontology and optionally select a single high-level category to search under.

## User story

*As a user* I want to be able to search the entire ontology for a symptom without constraint, or optionally limit my search to a single category.

*So that* I can find the symptoms that I seek if they are not found in the categories that I initially selected.

## Acceptance criteria

* User can perform an open-end search for any lay-person term in search index.
* User can perform a search for a term within a single phenotypic category.
* User can add the result to their collection of terms.
* Selected terms are identified as originating from the open-ended search rather than from the categorical search.

**Comment by heathharrelson** [comment]
The search input component now has two modes — filtered by category (used for the initial search) and user-selected filtering (used for the second search):

### Filtered by Category

<img width="907" alt="phenotypr-constrained" src="https://user-images.githubusercontent.com/2746306/44105259-fa990eba-9fa5-11e8-9da6-d96b864c4fa6.png">

### User-Selected Filter

![phenotypr-filtered-search](https://user-images.githubusercontent.com/2746306/44105275-05610f78-9fa6-11e8-8ed3-d5375012cbf7.png)

Persistence code has also been enhanced to keep track of which mode was used to select each term.
