### ISSUE TITLE
Enable Matching Exact Condition Names

### ISSUE THREAD

**Issue by heathharrelson** [OCTRI/phenotypr-body#75]
## Description

Suggested by @jmcmurry during review: In some cases, users may know the exact medical term for a condition. Because term labels aren't included in the fields searched, these searches fail. For example, searching for "vitiligo" will return no results, even though an exact match exists (HP:0001045). Enabling exact matches would be a nice improvement.

## Acceptance Criteria

* Users can find conditions by medical term in addition to lay synonyms

**Comment by heathharrelson** [comment]
I briefly looked at this on Thursday, and I was able to modify the search service to include the label field pretty easily. Unfortunately, the search is case sensitive, presumably because the label field isn't analyzed. @kshefchek, I assume this will require updating how things are indexed. Is that correct.

**Comment by kshefchek** [comment]
The primary label is not indexed in the same way, but I can update the solr schema fairly easily if this is desired.  I can work on it first thing Monday.

**Comment by kshefchek** [comment]
I have an untested PR here: https://github.com/monarch-initiative/hpo-plain-index/pull/4 that should allow this, but confirming with the PCORI leads that this is desired.

**Comment by mellybelly** [comment]
I think the idea was to have a secondary opportunity to include all HPO if the user did not find what they were looking for, at the very end?

**Comment by heathharrelson** [comment]
@mellybelly, this is in addition to being able to search against all of HPO. We implemented a mode where the whole HPO can be searched in #60 and #63, but that only searches the plain-language synonyms.

**Comment by kshefchek** [comment]
okay it seems I misunderstood the request.  For autocompleting on all of the HPO there are a few options:
- the biolink service: https://api.monarchinitiative.org/api/search/entity/autocomplete/vitil?prefix=HP&rows=20&start=0
- the solr service directly: https://solr.monarchinitiative.org/solr/search/select/?q=*:*&wt=json&rows=10&defType=edismax&qf=label&fq=prefix:HP

If there is a desire to boot up the solr service directly I can walk you through.  It is dockerized, but not as turn key as the lay person index.

**Comment by heathharrelson** [comment]
It's also possible that I don't understand the difference between searching all of the HPO and searching for terms without being filtered by the high-level systems. That being said, it seems like the system ought to return something if the user searches with the string "vitiligo", which currently results in the message "Nothing found." It may just take some additional discussion to accommodate Julie's request, should we decide to go forward with it.

![phenotypr-vitiligo-search](https://user-images.githubusercontent.com/2746306/44359926-11fdbe80-a46e-11e8-89c8-7457a390cc9b.png)

**Comment by kshefchek** [comment]
The index outputted by monarch-initiative/hpo-plain-index only contains a subset of the whole HPO (about 1/3).  See https://github.com/monarch-initiative/hpo-plain-index/blob/master/hpo-indexer/HPOIndexer/SolrLoader.py#L67

I could potentially refactor the index to pull all terms, and provide a boolean isLayPerson field so that these could be filtered when applicable.  This may be easier than dealing with two indexes, but I'm not sure I could get to it quickly (possibly by end of week if I'm over promising).

**Comment by heathharrelson** [comment]
@kshefchek I was looking at this speculatively in the hope of getting a quick win, but we haven't actually committed to working on this feature during the current sprint. I don't think there's any need to rush to refactor the index. Thanks for the quick replies — I hope I haven't caused you much unnecessary work.

**Comment by kshefchek** [comment]
nope not at all!

**Comment by kshefchek** [comment]
I've added a solrconfig for default fields and weights for all searchable fields: https://github.com/monarch-initiative/hpo-plain-index/blob/6d0b43/resources/conf/solrconfig.xml#L755

To search on only plain language terms would require to manually set the query field params, and add fq=has_pl_syn:true

To search on clinical and plain language terms just set the q param, eg:
https://solr-dev.monarchinitiative.org/solr/hpo-pl/select/?q=recurring%20nosebleed%20+%20%22recurring%20nosebleed%22&hl=on
