### ISSUE TITLE
Current groupings miss constitutional symptoms in HPO

### ISSUE THREAD

**Issue by kshefchek** [OCTRI/phenotypr-body#83]
I noticed that we're not able to autocomplete on "night sweats" and tracked it down to this being grouped under ["Constitutional symptom"](https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0025142) in the HPO.

My general sense is that this category should always be included as a default.  cc @jmcmurry @mellybelly

**Comment by kshefchek** [comment]
I'm failing to consider that a user would have an opportunity to submit these when selecting no to "Did you find all the symptoms you were searching for?"  There are also cases of multiple parentage where some of these terms would still show up under the preset categories.  The trade off of including this a default category is that some terms will be unrelated to what the user specifies.

**Comment by jmcmurry** [comment]
what is the number of constitutional terms as a percentage of all terms?

**Comment by jmcmurry** [comment]
Let's do include them then; I doubt it would be terribly intrusive but we will find out
